# -*- coding: utf-8 -*-
"""model_prediksi_stroke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqESmCyV_E8LcXP97DZ9W8MTqLDmTNzS

# Proyek Prediksi Analitik: Stroke Dataset
- **Nama:** Herly Riyanto Hidayat
- **Email:** herlynjjd@gmail.com
- **ID Dicoding:** herlyryanth

### Import dependecies
"""

# Commented out IPython magic to ensure Python compatibility.
# Import kaggle untuk mengambil data dari kaggle
import kagglehub

# Mengimpor libraries umum yang sering digunakan
import os, shutil
import zipfile
import pandas as pd
import tensorflow as tf
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

from imblearn.over_sampling import SMOTE

from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
!pip install xgboost
from xgboost import XGBClassifier
import warnings
from sklearn.metrics import accuracy_score, classification_report

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

"""### Exploratory Dataset

#### Data Loading
"""

source = kagglehub.dataset_download("fedesoriano/stroke-prediction-dataset")

# Define the destination path
destination_path = 'dataset'

# Move the dataset to the destination directory
shutil.copytree(source, destination_path)

print(f"Dataset downloaded and moved to {destination_path}")

"""#### Data reading"""

df = pd.read_csv("/content/dataset/healthcare-dataset-stroke-data.csv")
df.head(5)

"""#### Explore the data"""

df.info()

# Check the shape of dataframe
print("Shape of dataset: ", df.shape)

df.describe(include="all")

"""#### Drop irrelevant column"""

df = df.drop(columns="id")

"""#### Check Missing Value and Fix it

This section is to check the missing value of the dataset
"""

df.isnull().sum()

df.isna().sum()

"""From that's output we have conclusion that column bmi have missing value"""

# Fill the missing value using median
for col in df.columns:
  if df[col].isna().sum() > 0:
    df[col] = df[col].fillna(df[col].median())

df['bmi'].info()

# Check again
df.isnull().sum()

"""#### Check the duplicate values and fix it"""

df.duplicated().sum()

"""#### Check outliers"""

num_cols = df.select_dtypes(include="number").columns
for col in num_cols:
  plt.figure(figsize=(6, 2))
  sns.boxplot(x=df[col])
  plt.title(f'Outlier Check - {col}')
  plt.show()

"""This dataset have outliers but when we see the column, outliers didn't need to fix, because it's the parameters to decide it's stroke or not

#### Analysis Stroke Patient
"""

plt.figure(figsize=(8,5))
sns.countplot(x='stroke', data=df)
plt.title('Stroke Rate by Gender')
plt.ylabel('Proportion of Stroke')
plt.show()

"""#### Analysis Stroke based on Gender"""

gender = df['gender'].value_counts()
print(gender)

plt.figure(figsize=(8,5))
sns.barplot(x='gender', y='stroke', data=df)
plt.title('Stroke Rate by Gender')
plt.ylabel('Proportion of Stroke')
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x='stroke', y='age', hue='gender', data=df)
plt.title('Stroke Distribution by Age and Gender')
plt.show()

"""#### Analysis Stroke based on Smoking Status"""

smoking_status = df['smoking_status'].value_counts()
smoking_status

plt.figure(figsize=(8,5))
sns.barplot(x='smoking_status', y='stroke', data=df)
plt.title('Stroke Rate by Smoking Status')
plt.ylabel('Proportion of Stroke')
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x='stroke', y='age', hue='smoking_status', data=df)
plt.title('Stroke Distribution by Age and Smoking Status')
plt.show()

"""#### Analysis Correlation numeric features"""

plt.figure(figsize=(10, 8))
correlation_matrix = df[num_cols].corr().round(2)

sns.heatmap(data=correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5, )
plt.title("Correlation Matrics for Numeric Features ", size=20)

"""The numeric features not have correlation with target (stroke)

### Data Preparation

#### Encoding Categorical Features with Label Encoding
"""

df_preprocessed = df.copy()

# Get the categorical features
categorical_cols = df_preprocessed.select_dtypes(include='object').columns
categorical_cols

for col in categorical_cols:
  le= LabelEncoder()
  df_preprocessed[col] = le.fit_transform(df_preprocessed[col])
df_preprocessed.head(5)

df_preprocessed.corr().round(2)

"""#### Split Features and Target"""

# Split features and target to Standardization
feature = df_preprocessed.drop(columns=['stroke'])
target = df_preprocessed['stroke']

"""#### Standardization using StandardScaler()"""

# Data Transformation
scaler = StandardScaler()
data_scaled = pd.DataFrame(scaler.fit_transform(feature), columns=feature.columns)
data_scaled['stroke'] = target

data_scaled.head()

"""#### Data Splitting"""

# Split X (features) = all column except stroke, y (target) = stroke column
X = data_scaled.drop(columns=['stroke'])
y = data_scaled['stroke']

# Resampling Data using SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

# Splitting into Train (70%), Validation (15%), and Test Sets (15%)
X_train, X_temp, y_train, y_temp = train_test_split(X_res, y_res, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

"""### Modelling"""

# Random Forest
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)

# XGB Classifier
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(X_train, y_train)
xgb_preds = xgb_model.predict(X_test)

# Suppress warnings before fitting the XGBoost model
warnings.simplefilter("ignore", category=UserWarning)
warnings.simplefilter("ignore", category=FutureWarning)

# Deep Learning using Fully Connected Layer or Dense Neural Network (DNN)
model_dl = Sequential([
    Dense(32, input_shape=(X_train.shape[1],), activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')  # output 1 neuron for binary classification
])

model_dl.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model_dl.fit(X_train, y_train, epochs=10, batch_size=4, validation_data=(X_val, y_val))

"""### Evaluation"""

# Evaluation function
def evaluate_model(name, y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    cr = classification_report(y_test, y_pred)
    print(f"{name} Evaluation:\nAccuracy: {accuracy}\nClassification Report: \n{cr}")

evaluate_model("Random Forest Classifier", y_test, rf_preds)

evaluate_model("XGB Classifier", y_test, xgb_preds)

loss, accuracy = model_dl.evaluate(X_test, y_test)
print('Test Accuracy:', accuracy)

"""#### Hyperparameter Tuning for model Accuracy below 90%"""

!pip install keras-tuner -q
import keras_tuner as kt

def model_builder(hp):
  model = Sequential()
  model.add(Dense(units=hp.Int('units', min_value=32, max_value=128, step=32), activation='relu', input_shape=(X_train.shape[1],)))
  model.add(Dense(16, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))

  hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])

  model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=hp_learning_rate),
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

tuner = kt.Hyperband(model_builder,
                     objective='val_accuracy',
                     max_epochs=10,
                     factor=3,
                     directory='my_dir',
                     project_name='intro_to_kt')

tuner.search(X_train, y_train, epochs=10, validation_data=(X_val, y_val))

best_hps=tuner.get_best_hyperparameters(num_trials=1)[0]
model_dl=tuner.hypermodel.build(best_hps)
history = model_dl.fit(X_train, y_train, epochs=10, batch_size=4, validation_data=(X_val, y_val))

loss, accuracy = model_dl.evaluate(X_test, y_test)
print('Test Accuracy:', accuracy)

"""After doing Hyperparameter I got accuracy increase from 85% to 85,6%

### Testing
"""

# Create dictionary to save all model
model_dict = {'RandomForestClassiier': rf_model, 'XGBClassifier': xgb_model, 'DNN':model_dl}

# Get one sample data from X_test
data = X_test.iloc[:1].copy()

# Create a dictionary to save the predict of all model
pred_dict = {'y_true (nilai aktual)': y_test.iloc[:1].values}

# Variable to save prediction from convert the 0/1 label
convert_pred_label = ""
# Loop all model from model_dict
for name, model in model_dict.items():
    # Predict the probability
    pred = model.predict(data)

    # If the predict is array 2D, convert it to 1D
    if pred.ndim > 1:
        pred = pred.flatten()

    # For biner classification, change the probability to 0/1 label
    pred_label = (pred >= 0.5).astype(int)
    if pred_label == 0:
      convert_pred_label = "The patient not have probability stroke"
    else:
      convert_pred_label = "The patient have probability stroke"

    # Save the result of prediction model
    pred_dict['prediksi_' + name] = pred_label

# Show the dataframe predict
print(convert_pred_label)
pd.DataFrame(pred_dict)